name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      # Устанавливаем права для gradlew
      - name: Set executable permissions
        run: |
          chmod +x gradlew
          ls -la gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start application
        run: |
          java -jar ./artifacts/app-order.jar -port=8888 > app.log 2>&1 &
          sleep 20
          echo "=== Application logs ==="
          cat app.log
          echo "=== Network status ==="
          netstat -tulpn

      - name: Verify application
        run: |
          curl -v --retry 5 --retry-delay 5 http://localhost:8888

      - name: Run tests
        run: |
          ./gradlew test \
            -Dselenide.baseUrl=http://localhost:8888 \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            --stacktrace --info

      # Обновленная версия загрузки артефактов
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/test
            app.log
          retention-days: 1