name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start SUT (app-order.jar)
        run: |
          java -jar ./artifacts/app-order.jar &
          sleep 15  # Увеличенное время для запуска

      - name: Verify SUT is running
        run: |
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:9999

      - name: Run tests with Gradle
        run: ./gradlew test