name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start app
        run: |
          java -jar ./artifacts/app-order.jar -port=8888 &
          sleep 10
          curl http://localhost:8888

      - name: Run tests
        run: |
          ./gradlew test -Dselenide.baseUrl=http://localhost:8888