name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: --health-cmd "curl -f http://localhost:4444 || exit 1" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Verify artifacts
        run: |
          ls -la artifacts/
          [ -f artifacts/app-order.jar ] || exit 1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start application
        run: |
          java -jar ./artifacts/app-order.jar -port=8888 > app.log 2>&1 &
          sleep 15
          echo "=== App logs ==="
          cat app.log
          echo "=== Network status ==="
          netstat -tulpn
          echo "=== Checking port 8888 ==="
          curl -v --retry 5 --retry-delay 3 http://localhost:8888

      - name: Run tests with diagnostics
        run: |
          ./gradlew test \
            -Dselenide.baseUrl=http://localhost:8888 \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.headless=false \
            --stacktrace --info --no-daemon

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/test
            app.log
          retention-days: 1